__title__ = 'Python-JGraphT'
__description__ = 'Python JGraphT graph library.'
__url__ = 'https://jgrapht.org'
__version__ = '0.1.0'
__author__ = 'Dimitrios Michail'
__author_email__ = 'dimitrios.michail@gmail.com'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2020 Dimitrios Michail'
