__title__ = "JGraphT"
__description__ = "JGraphT library"
__url__ = "https://github.com/d-michail/python-jgrapht"
__version__ = "1.5.0.2"
__backend_version__ = "1.5.0"
__author__ = "Dimitrios Michail"
__author_email__ = "dimitrios.michail@gmail.com"
__license__ = "LGPL-2.1-or-later OR EPL-2.0"
__copyright__ = "2020 Dimitrios Michail"
__bibtex__ = """@article{jgrapht,
  title = {{J}{G}raph{T}--{A} {J}ava {L}ibrary for {G}raph {D}ata {S}tructures and {A}lgorithms},
  author = {Michail, Dimitrios and Kinable, Joris and Naveh, Barak and Sichi, John V.},
  year = {2020},
  issue_date = {May 2020},
  publisher = {Association for Computing Machinery},
  address = {New York, NY, USA},
  volume = {46},
  number = {2},
  journal = {ACM Trans. Math. Softw.},
  month = may,
  articleno = {16},
  numpages = {29},
}"""
